export type OrchestraSeedEntry = {
  canonical: string;
  aliases: string[];
  related?: string[];
};

// Seed curated from public orchestra lists and artist pages (Wikipedia, Todo Tango, MusicBrainz).
export const ORCHESTRA_SEED_DATA: OrchestraSeedEntry[] = [
  { canonical: "Anibal Troilo", aliases: ["Aníbal Troilo", "Troilo", "Orquesta Tipica Anibal Troilo", "Orquesta Típica Aníbal Troilo"] },
  { canonical: "Carlos Di Sarli", aliases: ["Di Sarli", "Carlos di Sarli", "Orquesta Tipica Carlos Di Sarli", "Orquesta Típica Carlos Di Sarli"] },
  { canonical: "Juan D'Arienzo", aliases: ["Juan D Arienzo", "D'Arienzo", "D Arienzo", "Orquesta Tipica Juan D'Arienzo", "Orquesta Típica Juan D'Arienzo"] },
  { canonical: "Osvaldo Pugliese", aliases: ["Pugliese", "Orquesta Osvaldo Pugliese", "Orquesta Tipica Osvaldo Pugliese"] },
  { canonical: "Francisco Canaro", aliases: ["Canaro", "Orquesta Francisco Canaro", "Orquesta Tipica Francisco Canaro"] },
  { canonical: "Alfredo De Angelis", aliases: ["De Angelis", "Alfredo de Angelis", "Orquesta Tipica Alfredo De Angelis"] },
  { canonical: "Miguel Caló", aliases: ["Miguel Calo", "Calo", "Caló", "Orquesta Tipica Miguel Calo", "Orquesta Típica Miguel Caló"] },
  { canonical: "Rodolfo Biagi", aliases: ["Biagi", "Orquesta Rodolfo Biagi", "Orquesta Tipica Rodolfo Biagi"] },
  { canonical: "Ricardo Tanturi", aliases: ["Tanturi", "Orquesta Ricardo Tanturi", "Orquesta Tipica Ricardo Tanturi"] },
  { canonical: "Angel D'Agostino", aliases: ["Ángel D'Agostino", "D'Agostino", "Angel D Agostino", "Orquesta Angel D'Agostino"] },
  { canonical: "Edgardo Donato", aliases: ["Donato", "Orquesta Tipica Donato", "Orquesta Edgardo Donato"] },
  { canonical: "Pedro Laurenz", aliases: ["Laurenz", "Orquesta Pedro Laurenz", "Orquesta Tipica Pedro Laurenz"] },
  { canonical: "Adolfo Carabelli", aliases: ["Carabelli", "Orquesta Adolfo Carabelli"] },
  { canonical: "Roberto Firpo", aliases: ["Firpo", "Orquesta Roberto Firpo", "Orquesta Tipica Roberto Firpo"] },
  { canonical: "Carlos Gardel", aliases: ["Gardel", "Carlos Gardel y sus guitarras"] },
  { canonical: "Julio De Caro", aliases: ["Julio de Caro", "De Caro", "Orquesta Julio De Caro"] },
  { canonical: "Francisco Lomuto", aliases: ["Lomuto", "Orquesta Francisco Lomuto"] },
  { canonical: "Francisco Rotundo", aliases: ["Rotundo", "Orquesta Francisco Rotundo"] },
  { canonical: "Domingo Federico", aliases: ["Federico", "Orquesta Domingo Federico"] },
  { canonical: "Lucio Demare", aliases: ["Demare", "Orquesta Lucio Demare"] },
  { canonical: "Jose Garcia", aliases: ["José García", "Garcia", "García", "Orquesta José García"] },
  { canonical: "Alberto Castillo", aliases: ["Castillo", "Alberto Castillo y su Orquesta"] },
  { canonical: "Carlos Figari", aliases: ["Figari", "Orquesta Carlos Figari"] },
  { canonical: "Armando Pontier", aliases: ["Pontier", "Orquesta Armando Pontier"] },
  { canonical: "Florindo Sassone", aliases: ["Sassone", "Orquesta Florindo Sassone"] },
  { canonical: "Alfredo Gobbi", aliases: ["Gobbi", "Alfredo Gobbi y su Orquesta"] },
  { canonical: "Enrique Rodriguez", aliases: ["Enrique Rodríguez", "Rodriguez", "Rodríguez", "Orquesta Enrique Rodriguez"] },
  { canonical: "Osvaldo Fresedo", aliases: ["Fresedo", "Orquesta Osvaldo Fresedo"] },
  { canonical: "Juan Maglio", aliases: ["Pacho", "Juan Maglio Pacho"] },
  { canonical: "Juan Canaro", aliases: ["Canaro Hermanos", "Juan y Francisco Canaro", "Orquesta Juan Canaro"] },
  { canonical: "Raul Kaplun", aliases: ["Raúl Kaplún", "Kaplun", "Kaplún", "Orquesta Raul Kaplun"] },
  { canonical: "Hector Varela", aliases: ["Héctor Varela", "Varela", "Orquesta Hector Varela"] },
  { canonical: "Hector Pacheco", aliases: ["Héctor Pacheco", "Pacheco", "Orquesta Hector Pacheco"] },
  { canonical: "Edgardo Donato y sus Muchachos", aliases: ["Donato y sus Muchachos"] },
  { canonical: "Alberto Nery", aliases: ["Nery", "Orquesta Alberto Nery"] },
  { canonical: "Angel Vargas", aliases: ["Ángel Vargas", "Vargas y su orquesta"] },
  { canonical: "Alberto Marino", aliases: ["Marino", "Alberto Marino y su Orquesta"] },
  { canonical: "Osmar Maderna", aliases: ["Maderna", "Orquesta Osmar Maderna"] },
  { canonical: "Braulio Galvan", aliases: ["Braulio Galván", "Galvan", "Galván"] },
  { canonical: "Emilio Balcarce", aliases: ["Balcarce", "Orquesta Emilio Balcarce"] },
  { canonical: "Carlos Posadas", aliases: ["Posadas"] },
  { canonical: "Francini Pontier", aliases: ["Francini-Pontier", "Orquesta Francini Pontier", "Orquesta Francini-Pontier"] },
  { canonical: "Atilio Stampone", aliases: ["Stampone", "Orquesta Atilio Stampone"] },
  { canonical: "Leopoldo Federico", aliases: ["L. Federico", "Leopoldo Federico y su Orquesta"] },
  { canonical: "Astor Piazzolla", aliases: ["Piazzolla", "Astor Piazzola", "Orquesta Astor Piazzolla", "Quinteto Astor Piazzolla"] },
  { canonical: "Sexteto Mayor", aliases: ["Sexteto Tango", "Sexteto Mayor Tango"] },
  { canonical: "Quinteto Real", aliases: ["Quinteto Tango Real"] },
  { canonical: "Color Tango", aliases: ["Orquesta Color Tango"] },
  { canonical: "El Arranque", aliases: ["Orquesta El Arranque"] },
  { canonical: "Sexteto Milonguero", aliases: ["Orquesta Sexteto Milonguero"] },
  { canonical: "Orquesta Tipica Victor", aliases: ["Orquesta Típica Victor", "Tipica Victor", "Típica Victor"] },
  { canonical: "Orquesta Tipica Brunswick", aliases: ["Orquesta Típica Brunswick", "Tipica Brunswick", "Típica Brunswick"] },
  { canonical: "Orquesta Tipica Select", aliases: ["Orquesta Típica Select"] },
  { canonical: "Bianco-Bachicha", aliases: ["Bianco Bachicha", "Orquesta Bianco-Bachicha"] },
  { canonical: "Jose Basso", aliases: ["José Basso", "Basso", "Orquesta Jose Basso"] },
  { canonical: "Carlos Garcia", aliases: ["Carlos García", "Garcia", "García", "Orquesta Carlos Garcia"] },
  { canonical: "Ricardo Malerba", aliases: ["Malerba", "Orquesta Ricardo Malerba"] },
  { canonical: "Emilio Orlando", aliases: ["Orlando", "Orquesta Emilio Orlando"] },
  { canonical: "Antonio Rodio", aliases: ["Rodio", "Orquesta Antonio Rodio"] },
  { canonical: "Angelica y Domingo", aliases: ["Angélica y Domingo"] },
  { canonical: "Alberto Echague", aliases: ["Alberto Echagüe", "Echague", "Echagüe"] },
  { canonical: "Enrique Campos", aliases: ["Campos"] },
  { canonical: "Joaquin Do Reyes", aliases: ["Joaquín Do Reyes", "Do Reyes"] },
  { canonical: "Alberto Podesta", aliases: ["Alberto Podestá", "Podesta", "Podestá"] },
  { canonical: "Julio Sosa", aliases: ["Sosa"] },
  { canonical: "Tito Reyes", aliases: ["Reyes"] },
  { canonical: "Tito Schipa", aliases: ["Schipa"] },
  { canonical: "Francisco Pracanico", aliases: ["Francisco Pracánico", "Pracanico", "Pracánico"] },
  { canonical: "Alberto Soifer", aliases: ["Soifer"] },
  { canonical: "Pedro Mafia", aliases: ["Pedro Maffia", "Mafia", "Maffia"] },
  { canonical: "Quinteto Pirincho", aliases: ["Pirincho"] },
  { canonical: "Los Tubatango", aliases: ["Tubatango"] },
  { canonical: "D'Arienzo y Biagi", aliases: ["D'Arienzo-Biagi", "D Arienzo y Biagi"] },
  { canonical: "Pedro Maffia y Sebastian Piana", aliases: ["Maffia-Piana"] },
  { canonical: "Edgardo Donato y Juan D'Arienzo", aliases: ["Donato y D'Arienzo"] },
  { canonical: "Horacio Salgan", aliases: ["Horacio Salgán", "Salgan", "Salgán", "Orquesta Horacio Salgan"] },
  { canonical: "Ruben Juarez", aliases: ["Rubén Juárez", "Juarez", "Juárez"] },
  { canonical: "Osvaldo Requena", aliases: ["Requena", "Orquesta Osvaldo Requena"] },
  { canonical: "Julio Ahumada", aliases: ["Ahumada", "Orquesta Julio Ahumada"] },
  { canonical: "Rodolfo Mederos", aliases: ["Mederos"] },
  { canonical: "Los Reyes del Tango", aliases: ["Reyes del Tango"] },
  { canonical: "Tango Bardo", aliases: ["Orquesta Tango Bardo"] },
  { canonical: "Orquesta Romantica Milonguera", aliases: ["Orquesta Romántica Milonguera", "Romantica Milonguera", "Romántica Milonguera"] },
  { canonical: "La Juan D'Arienzo", aliases: ["La Juan D Arienzo"] },
  { canonical: "Orquesta Escuela de Tango Emilio Balcarce", aliases: ["Orquesta Escuela Emilio Balcarce"] },
  { canonical: "Quinteto Angel", aliases: ["Quinteto Ángel"] },
  { canonical: "Lidia Borda y Daniel Godfrid", aliases: ["Lidia Borda"] },
  { canonical: "Ciriaco Ortiz", aliases: ["Ortiz"] },
  { canonical: "Adolfo Beron", aliases: ["Adolfo Berón"] },
  { canonical: "Donato Racciatti", aliases: ["Racciatti", "Orquesta Donato Racciatti"] },
  { canonical: "Luis Di Matteo", aliases: ["Di Matteo"] },
  { canonical: "Roberto Calo", aliases: ["Calo", "Caló"] },
  { canonical: "Atilio Bruni", aliases: ["Bruni"] },
  { canonical: "Julio Pollero", aliases: ["Pollero", "Orquesta Julio Pollero"] },
  { canonical: "Los Astros del Tango", aliases: ["Astros del Tango"] },
  { canonical: "Ricardo Ruiz", aliases: ["Ruiz"] },
  { canonical: "Orquesta Silencio", aliases: ["Silencio"] },
  { canonical: "Trio Pantaleon", aliases: ["Trio Pantaleón", "Pantaleon", "Pantaleón"] },
  { canonical: "Los Provincianos", aliases: ["Provincianos"] },
  { canonical: "Pablo Valle y su Orquesta", aliases: ["Pablo Valle"] },
  { canonical: "Tango Para Musicos", aliases: ["Tango para Músicos"] },
];
